[project]
name = "manashelper-bot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.24.0",
    "dishka>=1.7.2",
    "httpx>=0.28.1",
    "tzdata>=2025.3",
]
